### ISSUE TITLE
Unable to run more than 10 concurrent scripts

### ISSUE THREAD

**Issue by tafax** [folke/ultra-runner#122]
Hi,
I'm trying to run this scripts:
```
ultra -r --concurrency 20 --filter "@my-workspace/*" start
```

Unfortunately, even if I specified a `concurrency` of `20` I'm not able to run it on every package. It seems the concurrency is always limited to `10` (the default).

Do you have any advice?

**Comment by folke** [comment]
Just tested this, and it seems to work just fine on my end.

If you have packages depending on other packages in your repo, then those will be built before the dependents.

This is by design, so increasing concurrency makes no difference here.

This is needed, since otherwise you'd be building packages that depend on other packages that might not have been built yet.

Maybe that's the reason?
