### ISSUE TITLE
Yarn v2 (berry) support?

### ISSUE THREAD

**Issue by crubier** [folke/ultra-runner#137]
Hi, this package seems great! I having problems with it though, running on a monorepo with yarn v2. Is yarn v2 supported?

**Comment by folke** [comment]
Not for now. Looking at the documentation, it seems pretty straightforward to make `ultra` compatible.

[Call binaries using yarn run rather than node_modules/.bin](https://yarnpkg.com/getting-started/migration#call-binaries-using-yarn-run-rather-than-node_modulesbin)

I'll see if I can add support for berry somewhere this week.

**Comment by folke** [comment]
Fixed in the latest release v3.6.0 🚀
